config/routes.rb
Rails.application.routes.draw do

  mount Spree::Core::Engine, :at => '/'

end
Spree::Core::Engine.add_routes do

  namespace :admin do
    resources :tasks
    resources :shipments do
      member do
        post 'send_message'
      end
    end
  end

  resources :suppliers, only: [:show, :index]
  resources :conversations, only: [:show, :index, :create] do
    collection do
      post 'send_message'
    end
  end

  get 'products/:id/inquiry', to: 'products#inquiry', as: 'products_inquiry'
  post 'products/:id/inquiry', to: 'products#inquiry_create', as: 'products_inquiry_create'

  resources :tasks do
    member do
      get 'apply'
      post 'submit'
    end
  end
  resources :suppliers
  resources :balances do
    member do
      get 'pay'
    end
  end
  post 'balances/notify', to: 'balances#notify'
  
  resources :shipments do
    member do
      post 'send_message'
    end
  end
end

app/models/spree/task.rb
module Spree
  class Task < Spree::Base
    belongs_to :user

    validates :name, presence: true
  end
end

app/controllers/spree/admin/tasks_controller.rb
module Spree
  module Admin
    class TasksController < ResourceController
      before_action :load_task, only: [:show, :edit]
      create.before :create_before

      respond_to :html

      def index
        @tasks = spree_current_user.tasks
      end

      def show
      end

    private
      def load_task
        @task = spree_current_user.tasks.find(params[:id])
      end

      def create_before
        @object.user = spree_current_user
      end

    end
  end
end

app/controllers/spree/tasks_controller.rb
class Spree::TasksController < Spree::StoreController
  before_action :load_task, only: [:show, :apply, :submit]

  respond_to :html

  def index
    @tasks = Spree::Task.all
  end

  def apply
  end

  def submit
    receipt = spree_current_user.send_message(@task.user, params[:body], "New task")

    conversation = receipt.conversation
    conversation.create_info
    conversation.info.task = @task
    conversation.info.state = 2
    conversation.info.save
    redirect_to conversation_path(conversation)
  end

private
  def load_task
    @task = Spree::Task.find(params[:id])
  end

end

app/views/spree/admin/tasks/edit.html.erb
<%= form_for [:admin, @object], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="edit_task">
    <%= f.field_container :name, :class => ['form-group'] do %>
      <%= f.label :name, Spree.t(:name) %> <span class="required">*</span>
      <%= f.text_field :name, :class => 'form-control title' %>
      <%= f.error_message_on :name %>
    <% end %>

    <div data-hook="edit_task_attrs" class="row">

      <div data-hook="edit_task_description" class="col-md-4">
        <%= f.field_container :description, :class => ['form-group'] do %>
          <%= f.label :description, Spree.t(:master_description) %> <span class="required">*</span>
          <%= f.text_area :description, :class => 'form-control' %>
          <%= f.error_message_on :description %>
        <% end %>
      </div>

      <div data-hook="edit_task_is_available" class="col-md-4">
        <%= f.field_container :is_available, :class => ['form-group'] do %>
          <%= f.label :is_available, Spree.t(:is_available) %>
          <%= f.error_message_on :is_available %>
          <%= f.check_box :is_available, :class => 'form-control' %>
        <% end %>
      </div>

    </div>
    <div class="form-buttons actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'refresh' %>
    </div>

  </fieldset>
<% end %>

app/views/spree/admin/tasks/index.html.erb
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_task), new_object_url, { :class => "btn-success", :icon => 'add', :id => 'admin_new_task' } %>
<% end if can?(:create, Spree::Task) %>

<% if @tasks.any? %>
  <table class="table" id="listing_tasks">
    <thead>
      <tr data-hook="admin_tasks_index_headers">
        <th><%= Spree.t(:id) %></th>
        <th><%= Spree.t(:name) %></th>
        <th class="text-center">
          <%= Spree.t(:time) %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
          <tr id="<%= spree_dom_id task %>" data-hook="admin_tasks_index_rows" class="<%= cycle('odd', 'even') %>">
            <td class="id"><%= task.id %></td>
            <td><%= link_to task.try(:name), edit_admin_task_path(task) %></td>
            <td class="text-right">
              <%= task.updated_at.strftime("%H:%M:%S") %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

app/views/spree/admin/tasks/new.html.erb
<%= form_for [:admin, @object], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="new_task">
    <%= f.field_container :name, :class => ['form-group'] do %>
      <%= f.label :name, Spree.t(:name) %> <span class="required">*</span>
      <%= f.text_field :name, :class => 'form-control title' %>
      <%= f.error_message_on :name %>
    <% end %>

    <div data-hook="new_task_attrs" class="row">

      <div data-hook="new_task_description" class="col-md-4">
        <%= f.field_container :description, :class => ['form-group'] do %>
          <%= f.label :description, Spree.t(:master_description) %> <span class="required">*</span>
          <%= f.text_area :description, :class => 'form-control' %>
          <%= f.error_message_on :description %>
        <% end %>
      </div>

      <div data-hook="new_task_is_available" class="col-md-4">
        <%= f.field_container :is_available, :class => ['form-group'] do %>
          <%= f.label :is_available, Spree.t(:is_available) %>
          <%= f.error_message_on :is_available %>
          <%= f.check_box :is_available, :class => 'form-control' %>
        <% end %>
      </div>

    </div>
    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.create'), 'ok', 'submit', {class: 'btn-success'} %>
    </div>
  </fieldset>
<% end %>